### ISSUE TITLE
resources.conf should be called reference.conf

### ISSUE THREAD

**Issue by an-tex** [j5ik2o/akka-persistence-s3#60]
Hi!

First of all let me tell I think it's great idea to store snapshots in S3! I've tried using it but found a few rough edges, so there'll be more issues created ;) I'd be happy to create PRs for that myself, just let me know.

So, why I'm really here:
I think the resources.conf should be called reference.conf to be automatically included. 

Or at least there should be a reference.conf including defaults like
```
j5ik2o {
  s3-snapshot-store {
    class = "com.github.j5ik2o.akka.persistence.s3.snapshot.S3SnapshotStore"
    plugin-dispatcher = "akka.actor.default-dispatcher"
  }
}
```

**Comment by j5ik2o** [comment]
> I think the resources.conf should be called reference.conf to be automatically included.

Thank you for your feedback. Oh, Your feedback is correct.
This issue will be released with immediate corrections.

**Comment by j5ik2o** [comment]
shipped at https://github.com/j5ik2o/akka-persistence-s3/releases/tag/v1.0.13

**Comment by an-tex** [comment]
thanks for the quick fixes!
