### ISSUE TITLE
bucketNameResolver is always used

### ISSUE THREAD

**Issue by an-tex** [j5ik2o/akka-persistence-s3#61]
In `private def snapshotMetadatas` (https://github.com/j5ik2o/akka-persistence-s3/blob/master/snapshot/src/main/scala/com/github/j5ik2o/akka/persistence/s3/snapshot/S3SnapshotStore.scala#L270) the bucketNameResolver is used directly instead of calling `private def resolveBucketName` (https://github.com/j5ik2o/akka-persistence-s3/blob/master/snapshot/src/main/scala/com/github/j5ik2o/akka/persistence/s3/snapshot/S3SnapshotStore.scala#L82).

This leads to `override def loadAsync` (https://github.com/j5ik2o/akka-persistence-s3/blob/master/snapshot/src/main/scala/com/github/j5ik2o/akka/persistence/s3/snapshot/S3SnapshotStore.scala#L134) always using the bucketNameResolver instead of the config provided bucketName

**Comment by j5ik2o** [comment]
shipped at https://github.com/j5ik2o/akka-persistence-s3/releases/tag/v1.0.13
